trigger:
- main

variables:
  # Azure subscription and resource group details
  azureSubscriptionId: 'a51d7e3f-6bc9-4345-8670-d24facccf3ca'
  staticWebAppName: 'nice-beach-09658aa1e'  # Your Azure Static Web App name
  resourceGroup: 'MyWebApp_group'  # Resource group name for the static web app
  vmImageName: 'ubuntu-latest'  # Azure-hosted agent

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: Build
    displayName: 'Build and Test'
    pool:
      vmImage: $(vmImageName)  # Use Ubuntu hosted agent for the build

    steps:
    # Install Node.js
    - task: NodeTool@0
      inputs:
        versionSpec: '20.x'
      displayName: 'Install Node.js'

    # Install dependencies and run tests
    - script: |
        npm install
        npm test  # Execute Mocha tests
      displayName: 'Install Dependencies and Run Tests'

    # Archive build files (optional)
    - task: ArchiveFiles@2
      displayName: 'Archive Build Files'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        replaceExistingArchive: true

    # Publish the build artifacts
    - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      artifact: 'drop'
      displayName: 'Publish Build Artifacts'

- stage: Deploy
  displayName: 'Deploy to Azure Static Web App'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: Deploy
    displayName: 'Deploy to Azure Static Web App'
    pool:
      vmImage: $(vmImageName)  # Use Ubuntu agent for deployment

    steps:
    # Download the build artifact
    - download: current
      artifact: drop

    # Deploy to Azure Static Web App using AzureStaticWebApp@0 task
    - task: AzureStaticWebApp@0
      inputs:
        app_location: "/"  
        api_location: ""  
        output_location: "build"  # Adjust based on your build directory
        azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN)  # API token for authentication
      displayName: 'Deploy to Azure Static Web App'