trigger:
- main

variables:
  azureSubscription: '9a77c6b7-b89c-420d-9a92-2dc437472400'
  webAppName: 'MyWebApp'
  environmentName: 'Dev'
  vmImageName: 'ubuntu-latest'  

stages:
- stage: Build
  displayName: 'Build and Test Stage'
  jobs:
  - job: Build
    displayName: 'Build Job'
    pool:
      vmImage: $(vmImageName)

    steps:
    # Step 1: Install Node.js
    - task: NodeTool@0
      inputs:
        versionSpec: '20.x' 
      displayName: 'Install Node.js 20.x'

    # Step 2: Install dependencies using npm
    - script: |
        npm install  # Install dependencies
      displayName: 'Install Dependencies'

    # Step 3: Run tests using npm test
    - script: |
        npm test  # Execute Mocha tests
      displayName: 'Run Tests'

    # Step 4: Publish the build artifact for use in the deployment stage
    - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      artifact: 'drop'
      displayName: 'Publish Artifact'

- stage: Deploy
  displayName: 'Deploy Stage'
  dependsOn: Build
  condition: succeeded()  # Ensure deployment runs only if the build succeeds
  jobs:
  - deployment: Deploy
    displayName: 'Deploy to Azure Web App'
    environment: $(environmentName)
    pool:
      vmImage: $(vmImageName)  # Use Ubuntu agent for deployment
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current  # Download the artifact from the build stage
            artifact: drop

          # Step 6: Deploy to Azure Web App
          - task: AzureWebApp@1
            inputs:
              azureSubscription: $(azureSubscription)  # Your Azure subscription/service connection
              appType: webAppLinux
              appName: $(webAppName)  # Name of the Azure Web App
              runtimeStack: 'NODE|20-lts'  # Node.js 20 LTS runtime for the Web App
              package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
              startUpCommand: 'npm start'  # Ensure app starts with npm start
            displayName: 'Deploy to Azure Web App'